# Generated by Django 3.2.13 on 2024-04-01 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='body',
            new_name='text',
        ),
    ]
