# Generated by Django 3.2.13 on 2024-04-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_body_todo_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.TextField(max_length=500),
        ),
    ]
